image: rust:1.51.0


build:
  script:
    - apt-get update
    - apt-get install -y build-essential
    - rustup target add x86_64-apple-darwin
    - rustup target add x86_64-pc-windows-gnu
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target=x86_64-apple-darwin
    - cargo build --release --target=x86_64-pc-windows-gnu
    - cargo build --release --target=x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target
  only:
    - main
